require: rubocop-rails
Layout/LineLength:
  Max: 140
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  EnforcedStyle: unannotated
Style/Documentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Style/EmptyMethod:
  EnforcedStyle: expanded
